# **Data Cleaning & Preparation**

### Scalling/Standardize Data

### **Target Pertemuan**

<hr>

**Tujuan Instruksional Umum:** Peserta mampu mempersiapkan data untuk pembuatan model machine learning.

**Target Pertemuan:** Peserta mampu melakukan scaling/standardize data

<hr>

## **Scalling/Standardize Data**

Many machine learning algorithms work better when features are on a relatively similar scale and close to normally distributed. MinMaxScaler, RobustScaler, StandardScaler, and Normalizer are scikit-learn methods to preprocess data for machine learning. Which method you need, if any, depends on your model type and your feature values.

As often as these methods appear in machine learning workflows, I found it difficult to find information about which of them to use when. Commentators often use the terms scale, standardize, and normalize interchangeably. However, their are some differences and the four scikit-learn functions we will examine do different things.

### **What is Scale, Standardize and Normalize?**

* **Scale** generally means to change the range of the values. The shape of the ``distribution doesn’t change``. Think about how a scale model of a building has the same proportions as the original, ``just smaller``. That’s why we say it is drawn to scale. The range is often set at 0 to 1.

* **Standardize** generally means changing the values so that the distribution standard deviation from the mean equals one. It outputs something ``very close to a normal distribution``. Scaling is often implied.

* **Normalize** can be used to mean either of the above things (and more!). I suggest you avoid the term normalize, because it has many definitions and is prone to creating confusion.

### **Why we need them?**
Many ``machine learning algorithms perform better`` or converge faster when ``features are on a relatively similar scale`` and/or ``close to normally distributed``.

Scaling and standardizing can help features arrive in more digestible form for these algorithms.

## **How to scaling/standardize data?**
Standardization is a transformation that centers the data by removing the mean value of each feature and then scale it by dividing (non-constant) features by their standard deviation. After standardizing data the mean will be zero and the standard deviation one.

Standardization can drastically improve the performance of models. For instance, many elements used in the objective function of a learning algorithm (such as the RBF kernel of Support Vector Machines or the l1 and l2 regularizers of linear models) assume that all features are centered around zero and have variance in the same order. If a feature has a variance that is orders of magnitude larger than others, it might dominate the objective function and make the estimator unable to learn from other features correctly as expected.

Depending on your needs and data, sklearn provides a bunch of scalers: StandardScaler, MinMaxScaler, MaxAbsScaler and RobustScaler.

### **1. StandardScaler**
The standard scaler __assumes our data is normally distributed within each feature__ and will scale them such that the ``distribution is now centred around 0``, with a ``standard deviation of 1``. StandardScaler, uses a strict definition of standardization to standardize data. It purely centers the data by using the following formula, where u is the mean and s is the standard deviation.

``x_scaled = (x — u) / s``

``x_scaled = xi–mean(x)/stdev(x)``

StandardScaler standardizes a feature by subtracting the mean and then scaling to unit variance. Unit variance means dividing all the values by the standard deviation. StandardScaler does not meet the strict definition of scale I introduced earlier.

``If data is not normally distributed, this is not the best scaler to use.``

**StandardScaler results** in a distribution with a **standard deviation equal to 1**. The variance is equal to 1 also, because variance = standard deviation squared. And 1 squared = 1.

StandardScaler makes the **mean of the distribution 0**. About 68% of the values will lie be between -1 and 1.

Deep learning algorithms often call for zero mean and unit variance. Regression-type algorithms also benefit from normally distributed data with small sample sizes.

StandardScaler does distort the relative distances between the feature values, so it’s generally my second choice in this family of transformations.

### **2. MinMaxScaler**
``This scaler works better for cases in which the standard scaler might not work so well.`` The MinMaxScaler transforms features by **scaling each feature to a given range**. This range can be set by specifying the feature_range parameter (default at (0,1)). This scaler works better for cases where the distribution is not Gaussian or the standard deviation is very small. However, it is **sensitive to outliers**, so if there are outliers in the data, you might want to consider another scaler (``Robust Scaler``).
 


> ``x_scaled = (x-min(x)) / (max(x)–min(x))``

<img src = "a_img.png" style="width:250px;height:150px"/>

For each value in a feature, MinMaxScaler subtracts the minimum value in the feature and then divides by the range. The range is the difference between the original maximum and original minimum.

MinMaxScaler preserves the shape of the __original distribution__. It doesn’t meaningfully change the information embedded in the original data.

Note that MinMaxScaler doesn’t reduce the importance of outliers.

The default range for the feature returned by MinMaxScaler is __0 to 1__.

> ``MinMaxScaler is a good place to start unless you know you want your feature to have a normal distribution or want outliers to have reduced influence.``

### **2. MaxAbs Scaler**
The MaxAbsScaler works very similarly to the MinMaxScaler but automatically scales the data to a [-1,1] range based on the **absolute maximum**. This scaler is meant for **data that is already centered at zero or sparse data**. It does not shift/center the data, and thus does not destroy any sparsity.

``x_scaled = x / max(abs(x))``

### **4. RobustScaler**
If your data contains **many outliers**, scaling using the mean and standard deviation of the data is likely to not work very well. In these cases, you can use the *RobustScaler*. **It removes the median and scales the data according to the quantile range.** 

By default, the scaler uses the Inter Quartile Range (IQR), which is the range between the 1st quartile and the 3rd quartile. The quantile range can be manually set by specifying the quantile_range parameter when initiating a new instance of the RobustScaler. Here, we transform feature 3 using an quantile range from 10% till 90%.

RobustScaler transforms the feature vector by subtracting the median and then dividing by the interquartile range (75% value — 25% value).

Like MinMaxScaler, our feature with large values — normal-big — is now of similar scale to the other features. Note that RobustScaler does not scale the data into a predetermined interval like MinMaxScaler. It does not meet the strict definition of scale I introduced earlier.

``The Robust Scaler uses a similar method to the Min-Max scaler but it instead uses the interquartile range, rather than the min-max, so that it is robust to outliers. ``

Therefore it follows the formula:

`` xi–Q2(x) / Q3(x)–Q1(x) ``

Note that the range for each feature after RobustScaler is applied is larger than it was for MinMaxScaler.

> ``Use RobustScaler if you want to reduce the effects of outliers, relative to MinMaxScaler.``

### **5. Normalizer**
> Normalization is the process of scaling individual samples to have unit norm. In basic terms you need to normalize data when the algorithm predicts based on the weighted relationships formed between data points. Scaling inputs to unit norms is a common operation for text classification or clustering.

Normalizer works on __the rows, not the columns__! I find that very unintuitive. It’s easy to miss this information in the docs.

By default, L2 normalization is applied to each observation so the that the values in a row have a unit norm. Unit norm with L2 means that if each element were squared and summed, the total would equal 1. Alternatively, L1 (aka taxicab or Manhattan) normalization can be applied instead of L2 normalization.

Normalizer does transform all the features to values between -1 and 1 (this text updated July 2019). In our example, normal_big ends up with all its values transformed to .9999999.

## **Conclusion**
* Use __MinMaxScaler__ as the __default__ if you are transforming a feature. It’s non-distorting.
* You could use __RobustScale__r if you have __outliers__ and want to reduce their influence. However, you might be better off removing the outliers, instead.
* Use __StandardScale__r if you need a __relatively normal distribution__.
* Use Normalizer sparingly — it normalizes sample rows, not feature columns. It can use l2 or l1 normalization.

<hr>

## __Scalling/Standardize Melbourne Housing Dataset__

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import RobustScaler

#tambahan
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import Binarizer

In [2]:
df = pd.read_csv('melb_data.csv')
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [4]:
df = df[['Price', 'Distance', 'Car', 'Landsize', 'Rooms', 'Bedroom2', 'Bathroom']]
df.head()

       Price  Distance  Car  Landsize  Rooms  Bedroom2  Bathroom
0  1480000.0       2.5  1.0     202.0      2       2.0       1.0
1  1035000.0       2.5  0.0     156.0      2       2.0       1.0
2  1465000.0       2.5  0.0     134.0      3       3.0       2.0
3   850000.0       2.5  1.0      94.0      3       3.0       2.0
4  1600000.0       2.5  2.0     120.0      4       3.0       1.0

## **1. Standard Scaler**
Standard Scaler digunakan pada data yang berdistribusi normal, tapi kalau data cenderung tidak normal, scaler ini akan 'memaksa' data berdistribusi normal.

In [5]:
# melakukan Standard Scaling pada feature 'Price'
SScaler = StandardScaler()
Price_scl = SScaler.fit_transform(df[['Price']])
df['Price_SScaler'] = Price_scl
df.head()

,Price,Distance,Car,Landsize,Rooms,Bedroom2,Bathroom,Price_SScaler
0,1480000.0,2.5,1.0,202.0,2,2.0,1.0,0.632448
1,1035000.0,2.5,0.0,156.0,2,2.0,1.0,-0.063640
2,1465000.0,2.5,0.0,134.0,3,3.0,2.0,0.608984
3,850000.0,2.5,1.0,94.0,3,3.0,2.0,-0.353025
4,1600000.0,2.5,2.0,120.0,4,3.0,1.0,0.820157

In [9]:
df['Price_SScaler2'] = StandardScaler().fit_transform(df[['Price']])
df.head()

,Price,Distance,Car,Landsize,Rooms,Bedroom2,Bathroom,Price_SScaler,Price_SScaler2
0,1480000.0,2.5,1.0,202.0,2,2.0,1.0,0.632448,0.632448
1,1035000.0,2.5,0.0,156.0,2,2.0,1.0,-0.063640,-0.063640
2,1465000.0,2.5,0.0,134.0,3,3.0,2.0,0.608984,0.608984
3,850000.0,2.5,1.0,94.0,3,3.0,2.0,-0.353025,-0.353025
4,1600000.0,2.5,2.0,120.0,4,3.0,1.0,0.820157,0.820157

In [6]:
df['Price_SScaler'].std()

1.0000368208848183

In [10]:
df['Price_SScaler'].mean()

1.4441074747407044e-16

In [8]:
df['Price_SScaler'].median()

-0.27011972625023595

## **2. MinMax Scaler**
Minmax Scaler digunakan pada kondisi feature yang tidak ada outliers. Bekerja dengan baik jika datanya tidak ada outlier. Karena MinMax Scaler sensitif dengan outlier. MinMax Scaler tidak mengitervensi data agar berdistribusi normal. MinMax Scaler hanya mengubah scale-nya saja.

In [11]:
df['Price_MinMax'] = MinMaxScaler().fit_transform(df[['Price']])
df.head()

,Price,Distance,Car,Landsize,Rooms,Bedroom2,Bathroom,Price_SScaler,Price_SScaler2,Price_MinMax
0,1480000.0,2.5,1.0,202.0,2,2.0,1.0,0.632448,0.632448,0.156478
1,1035000.0,2.5,0.0,156.0,2,2.0,1.0,-0.063640,-0.063640,0.106562
2,1465000.0,2.5,0.0,134.0,3,3.0,2.0,0.608984,0.608984,0.154795
3,850000.0,2.5,1.0,94.0,3,3.0,2.0,-0.353025,-0.353025,0.085810
4,1600000.0,2.5,2.0,120.0,4,3.0,1.0,0.820157,0.820157,0.169938

## __3. MaxAbs Scaler__
MaxAbs Scaler dipakai ketika datanya tidak ada outlier. Hampir sama dengan MinMax Scaler.

In [13]:
df['Price_MaxAbs'] = MaxAbsScaler().fit_transform(df[['Price']])
df.head()

,Price,Distance,Car,Landsize,Rooms,Bedroom2,Bathroom,Price_SScaler,Price_SScaler2,Price_MinMax,Price_MaxAbs
0,1480000.0,2.5,1.0,202.0,2,2.0,1.0,0.632448,0.632448,0.156478,0.164444
1,1035000.0,2.5,0.0,156.0,2,2.0,1.0,-0.063640,-0.063640,0.106562,0.115000
2,1465000.0,2.5,0.0,134.0,3,3.0,2.0,0.608984,0.608984,0.154795,0.162778
3,850000.0,2.5,1.0,94.0,3,3.0,2.0,-0.353025,-0.353025,0.085810,0.094444
4,1600000.0,2.5,2.0,120.0,4,3.0,1.0,0.820157,0.820157,0.169938,0.177778

## __4. Robust Scaler__
Robust Scaler dipakai ketika feature memailiki data **outlier**, karena Scaler ini **tidak** mendasarkan rumusnya dengan mean atau standart deviasi. Tapi Scaler ini dasar teorinya menggunakan IQR. Sehingga lebih tahan (robust) dengan adanya data outliers.

In [14]:
df['Price_Robust'] = RobustScaler().fit_transform(df[['Price']])
df.head()

,Price,Distance,Car,Landsize,Rooms,Bedroom2,Bathroom,Price_SScaler,Price_SScaler2,Price_MinMax,Price_MaxAbs,Price_Robust
0,1480000.0,2.5,1.0,202.0,2,2.0,1.0,0.632448,0.632448,0.156478,0.164444,0.848529
1,1035000.0,2.5,0.0,156.0,2,2.0,1.0,-0.063640,-0.063640,0.106562,0.115000,0.194118
2,1465000.0,2.5,0.0,134.0,3,3.0,2.0,0.608984,0.608984,0.154795,0.162778,0.826471
3,850000.0,2.5,1.0,94.0,3,3.0,2.0,-0.353025,-0.353025,0.085810,0.094444,-0.077941
4,1600000.0,2.5,2.0,120.0,4,3.0,1.0,0.820157,0.820157,0.169938,0.177778,1.025000

## 5. Normalizer & Binarizer (TAMBAHAN)
Normalizer sebenarnya bekerja di _row_ (baris) bukan kolom. Pada praktik di bawah ini diterapkan pada kolom _Price__

In [15]:
df['Price_Nrmlzr'] = Normalizer().fit_transform(df[['Price']])
df.head()

,Price,Distance,Car,Landsize,Rooms,Bedroom2,Bathroom,Price_SScaler,Price_SScaler2,Price_MinMax,Price_MaxAbs,Price_Robust,Price_Nrmlzr
0,1480000.0,2.5,1.0,202.0,2,2.0,1.0,0.632448,0.632448,0.156478,0.164444,0.848529,1.0
1,1035000.0,2.5,0.0,156.0,2,2.0,1.0,-0.063640,-0.063640,0.106562,0.115000,0.194118,1.0
2,1465000.0,2.5,0.0,134.0,3,3.0,2.0,0.608984,0.608984,0.154795,0.162778,0.826471,1.0
3,850000.0,2.5,1.0,94.0,3,3.0,2.0,-0.353025,-0.353025,0.085810,0.094444,-0.077941,1.0
4,1600000.0,2.5,2.0,120.0,4,3.0,1.0,0.820157,0.820157,0.169938,0.177778,1.025000,1.0

__Binarizer__ bisa dipakai untuk seleksi suatu kolom dengan kondisi tertentu.

``Contoh``: Pada contoh dibawah ini dipakai untuk menandai Bathroom jika di atas 2 maka diberi tanda/simbol 1 (True). Sebaliknya diberi tanda 0 (False). Lalu, disimpan dalam kolom baru dengan nama _Binarizer_Bathroom_

In [16]:
df['Binarizer_Bathroom'] = Binarizer(threshold = 2).fit_transform(df[['Bathroom']])
df.head()

,Price,Distance,Car,Landsize,Rooms,Bedroom2,Bathroom,Price_SScaler,Price_SScaler2,Price_MinMax,Price_MaxAbs,Price_Robust,Price_Nrmlzr,Binarizer_Bathroom
0,1480000.0,2.5,1.0,202.0,2,2.0,1.0,0.632448,0.632448,0.156478,0.164444,0.848529,1.0,0.0
1,1035000.0,2.5,0.0,156.0,2,2.0,1.0,-0.063640,-0.063640,0.106562,0.115000,0.194118,1.0,0.0
2,1465000.0,2.5,0.0,134.0,3,3.0,2.0,0.608984,0.608984,0.154795,0.162778,0.826471,1.0,0.0
3,850000.0,2.5,1.0,94.0,3,3.0,2.0,-0.353025,-0.353025,0.085810,0.094444,-0.077941,1.0,0.0
4,1600000.0,2.5,2.0,120.0,4,3.0,1.0,0.820157,0.820157,0.169938,0.177778,1.025000,1.0,0.0

In [17]:
df['Binarizer_Bathroom'].value_counts()

0.0    12520
1.0     1060
Name: Binarizer_Bathroom, dtype: int64

<hr>

# **SCALLING/STANDARDIZE EXERCISE**
- Gunakan data Melb_data.csv
- ``Price`` adalah target sehingga tidak perlu di-scalling. Sedangkan feature ``Distance, Car, Landsize, Rooms, Bedroom2, Bathroom`` adalah feature yang harus di-scalling.
- ``Data NaN`` (meskipun bukan best practice) ``dihapus`` saat sudah menjadi df_test (sudah dipilih feature-nya).
- Gunakan ``Scaler yang tepat`` dengan kondisi data! (Cek ada outliers atau tidak)
- Simpan ke dalam ``dataframe baru`` yang berisi target (Price) dan feature Distance, Car, Landsize, Rooms, Bedroom2, Bathroom yang sudah di-scaling.

### **Step to step**
1. Drop all missing values
2. Cek outliers tiap feature
3. Scalling sesuai kondisi feature
4. Simpan dalam df_ready

### __Take Home Exercise__

#### - Buat visualisasi untuk menampilkan distribusi data pada feature sebelum dan sesudah dilakukan scalling/standardize!

<hr>

## **Reference**:
* Jeff Hale, "Scale, Standardize, or Normalize with Scikit-Learn", https://towardsdatascience.com/scale-standardize-or-normalize-with-scikit-learn-6ccc7d176a02
* Robert R.F. DeFilippi, "Standardize or Normalize? — Examples in Python", https://medium.com/@rrfd/standardize-or-normalize-examples-in-python-e3f174b65dfc
* Shubham Panchal, "Standardization on Crazy Data-Python", https://medium.com/predict/standardization-on-crazy-data-python-cd5b1282a97f
* Shubham Panchal, "Normalization of Crazy Data — Python", https://medium.com/@equipintelligence/normalization-of-crazy-data-python-4fa6611e7b46
* Steven Van Dorpe, "Preprocessing with sklearn: a complete and comprehensive guide", https://towardsdatascience.com/preprocessing-with-sklearn-a-complete-and-comprehensive-guide-670cb98fcfb9
* Nem Kumar Kothari, "Feature Scaling in Machine Learning", https://medium.com/@nemkothari/feature-scaling-in-machine-learning-10e2ca2fe2d9